import { FormEvent, useState } from "react";
import { api } from "../api";
import { CATEGORY_LABEL, KIND_LABEL, when } from "../format";
import type { CaseDetail, Finding, MissingEvidence } from "../types";
import { Cites, Empty, ErrorBlock, Field, Modal, Pill, Spinner, useToast } from "./ui";

export default function InvestigationTab({ detail, onChanged, onTab, running }: { detail: CaseDetail; onChanged: () => void; onTab: (t: string) => void; running: boolean }) {
  const a = detail.latest_analysis;
  const [requesting, setRequesting] = useState<MissingEvidence | null>(null);
  const [filter, setFilter] = useState<string>("all");

  if (!a) {
    return (
      <Empty title={running ? "The analysis is running" : "No analysis yet"}>
        {running ? <p>Findings will appear here when the agent finishes.</p> : (
          <p>Check the evidence is complete, then run the analysis. The invoice is recalculated by code first; the AI then
            explains the differences, cites the records behind each conclusion, and proposes options for you to decide.</p>
        )}
        {!running && <button className="btn" onClick={() => onTab("evidence")}>Review evidence</button>}
      </Empty>
    );
  }

  const openReqs = detail.info_requests.filter((r) => r.status === "open");
  const counts = a.findings.reduce<Record<string, number>>((m, f) => { m[f.status] = (m[f.status] || 0) + 1; return m; }, {});
  const shown = a.findings.filter((f) => filter === "all" || (filter === "open" ? f.status === "proposed" : f.status === filter));
  const gr = a.guardrail_report || {};

  return (
    <div className="inv">
      <section className="summary">
        <div className="summary-head">
          <h2>Case summary</h2>
          <SourceBadge source={a.source} provider={a.provider} model={a.model} />
          <span className="muted">{when(a.created_at)}</span>
        </div>
        {a.source !== "llm" && (
          <div className="callout callout-info">
            {a.source === "fallback"
              ? "The model was unavailable for this run, so this analysis was generated by deterministic rules. It is accurate but plainer, and it cannot weigh supporting notes. Re-run when the model is available."
              : "Part of this analysis came from the deterministic fallback because the model's output was unusable."}
          </div>
        )}
        <p className="ai-text">{a.case_summary}</p>
        {a.claim_assessment && <><h3 className="sub">The customer's claim</h3><p className="ai-text">{a.claim_assessment}</p></>}
        <p className="guard-line">
          Checked by the guardrails: {gr.citations_checked ?? 0} citations, {gr.citations_invalid ?? 0} removed as unmatched,
          {" "}{gr.recategorized ?? 0} findings recategorized, {gr.unverified_numbers ?? 0} unverified figures.
          {(gr.notes || []).map((n: string, i: number) => <span key={i} className="guard-note"> {n}</span>)}
        </p>
      </section>

      {(a.missing_evidence.length > 0 || openReqs.length > 0) && (
        <section className="missing">
          <h2>Missing evidence</h2>
          <ul className="missing-list">
            {a.missing_evidence.map((m, i) => {
              const req = openReqs.find((r) => r.evidence_kind === m.evidence_kind);
              const have = detail.evidence.some((e) => e.active && e.kind === m.evidence_kind);
              return (
                <li key={i} className={m.blocking ? "is-blocking" : ""}>
                  <div>
                    <strong>{KIND_LABEL[m.evidence_kind] || m.evidence_kind}</strong>
                    {m.blocking && <Pill tone="red">Blocks a conclusion</Pill>}
                    {m.source !== "engine" && <Pill tone="carbon">Suggested by the AI</Pill>}
                    <p>{m.reason}</p>
                  </div>
                  {req ? <span className="muted">Requested ({req.id})</span>
                    : have && a.stale ? <span className="muted">Added since; re-run</span>
                    : <button className="btn btn-sm" onClick={() => setRequesting(m)}>Request it</button>}
                </li>
              );
            })}
          </ul>
        </section>
      )}

      <section>
        <div className="findings-head">
          <h2>Findings</h2>
          <div className="seg" role="group" aria-label="Filter findings">
            {[["all", `All ${a.findings.length}`], ["open", `To review ${counts.proposed || 0}`], ["accepted", `Accepted ${(counts.accepted || 0) + (counts.edited || 0)}`], ["rejected", `Rejected ${counts.rejected || 0}`]].map(([k, l]) => (
              <button key={k} className={filter === k ? "is-on" : ""} onClick={() => setFilter(k)}>{l}</button>
            ))}
          </div>
        </div>
        {shown.length === 0 && <p className="muted">No findings in this view.</p>}
        <div className="findings">
          {shown.map((f) => <FindingCard key={f.id} f={f} onChanged={onChanged} />)}
        </div>
        {(counts.proposed || 0) === 0 && a.findings.length > 0 && (
          <div className="next-step">
            All findings are reviewed. <button className="link-btn" onClick={() => onTab("resolution")}>Choose a resolution</button>
          </div>
        )}
      </section>

      {requesting && <RequestDialog caseId={detail.case.id} need={requesting} onClose={() => setRequesting(null)} onDone={() => { setRequesting(null); onChanged(); }} />}
    </div>
  );
}

function SourceBadge({ source, provider, model }: { source: string; provider: string; model: string }) {
  if (source === "llm") return <Pill tone="carbon">AI analysis, {provider} {model}</Pill>;
  if (source === "hybrid") return <Pill tone="amber">AI with deterministic fill-in</Pill>;
  return <Pill tone="amber">Deterministic fallback</Pill>;
}

const CAT_TONE: Record<string, string> = {
  calculation_error: "red", contract_interpretation: "amber", data_quality: "ink", customer_misunderstanding: "green", needs_evidence: "grey",
};

function FindingCard({ f, onChanged }: { f: Finding; onChanged: () => void }) {
  const toast = useToast();
  const [busy, setBusy] = useState<string | null>(null);
  const [error, setError] = useState<unknown>(null);
  const [mode, setMode] = useState<"edit" | "reject" | null>(null);
  const ungrounded = f.flags.includes("ungrounded");
  const stale = f.stale_reasons.length > 0;
  const flags = f.flags.filter((x) => x !== "ungrounded");

  async function act(action: string, body: Record<string, unknown> = {}) {
    setBusy(action); setError(null);
    try {
      await api(`/api/findings/${f.id}`, { method: "PATCH", body: { action, ...body } });
      toast("ok", action === "accept" ? "Finding accepted." : action === "reject" ? "Finding rejected." : action === "edit" ? "Finding edited and accepted." : "Review undone.");
      setMode(null);
      onChanged();
    } catch (e) { setError(e); } finally { setBusy(null); }
  }

  return (
    <article className={`finding finding-${f.status} ${stale ? "is-stale" : ""}`}>
      <div className="finding-top">
        <span className={`cat cat-${CAT_TONE[f.category] || "grey"}`}>{CATEGORY_LABEL[f.category] || f.category}</span>
        <span className="muted">Confidence {f.confidence}</span>
        {f.status !== "proposed" && <span className={`review review-${f.status}`}>{f.status === "edited" ? "Edited and accepted" : f.status === "accepted" ? "Accepted" : "Rejected"} by {f.reviewed_by}</span>}
      </div>
      <h3>{f.title}</h3>
      <p className={f.status === "edited" ? "" : "ai-text"}>{f.explanation}</p>
      {f.original && <details className="orig"><summary>Original AI wording</summary><p className="ai-text"><strong>{f.original.title}.</strong> {f.original.explanation}</p></details>}
      <div className="finding-cites"><span className="muted">Based on</span> <Cites list={f.citations} /></div>
      {stale && <div className="flag flag-stale">Relies on {f.stale_reasons.join(", ")} evidence that has changed since this analysis.</div>}
      {ungrounded && <div className="flag flag-red">No valid citation. This finding can't be accepted; reject it or re-run the analysis.</div>}
      {flags.map((x, i) => <div key={i} className="flag">{x}</div>)}
      {f.reviewer_note && <p className="note">Reviewer note: {f.reviewer_note}</p>}
      <ErrorBlock error={error} />
      <div className="finding-actions">
        {f.status === "proposed" ? (
          <>
            <button className="btn btn-accept btn-sm" disabled={!!busy || ungrounded || stale} onClick={() => act("accept")}>{busy === "accept" ? <Spinner /> : "Accept"}</button>
            <button className="btn btn-sm" disabled={!!busy || stale} onClick={() => setMode("edit")}>Edit</button>
            <button className="btn btn-sm btn-quiet" disabled={!!busy} onClick={() => setMode("reject")}>Reject</button>
          </>
        ) : (
          <button className="link-btn" disabled={!!busy} onClick={() => act("reset")}>Undo review</button>
        )}
      </div>
      {mode && <ReviewDialog f={f} mode={mode} busy={!!busy} error={error} onClose={() => setMode(null)} onSubmit={(b) => act(mode, b)} />}
    </article>
  );
}

function ReviewDialog({ f, mode, busy, error, onClose, onSubmit }: { f: Finding; mode: "edit" | "reject"; busy: boolean; error: unknown; onClose: () => void; onSubmit: (b: Record<string, unknown>) => void }) {
  const [title, setTitle] = useState(f.title);
  const [explanation, setExplanation] = useState(f.explanation);
  const [category, setCategory] = useState(f.category);
  const [note, setNote] = useState("");
  const [err, setErr] = useState("");
  function submit(e: FormEvent) {
    e.preventDefault();
    if (note.trim().length < 3) { setErr(mode === "edit" ? "Say what you changed and why." : "Say why this finding is wrong."); return; }
    onSubmit(mode === "edit" ? { title, explanation, category, note } : { note });
  }
  return (
    <Modal title={mode === "edit" ? "Edit finding" : "Reject finding"} onClose={onClose}>
      <form onSubmit={submit} noValidate>
        {mode === "edit" && (
          <>
            <Field label="Headline"><input value={title} onChange={(e) => setTitle(e.target.value)} /></Field>
            <Field label="Category">
              <select value={category} onChange={(e) => setCategory(e.target.value)}>
                {Object.entries(CATEGORY_LABEL).map(([k, v]) => <option key={k} value={k}>{v}</option>)}
              </select>
            </Field>
            <Field label="Explanation"><textarea rows={6} value={explanation} onChange={(e) => setExplanation(e.target.value)} /></Field>
          </>
        )}
        {mode === "reject" && <p className="muted">“{f.title}”</p>}
        <Field label={mode === "edit" ? "Reason for the edit" : "Reason for rejecting"} error={err} hint="Saved to the case history.">
          <textarea rows={3} value={note} onChange={(e) => setNote(e.target.value)} />
        </Field>
        <ErrorBlock error={error} />
        <div className="modal-actions">
          <button type="button" className="btn btn-quiet" onClick={onClose}>Cancel</button>
          <button className={`btn ${mode === "reject" ? "btn-danger" : "btn-primary"}`} disabled={busy}>{busy ? <Spinner /> : mode === "edit" ? "Save and accept" : "Reject finding"}</button>
        </div>
      </form>
    </Modal>
  );
}

export function RequestDialog({ caseId, need, onClose, onDone }: { caseId: string; need: MissingEvidence | null; onClose: () => void; onDone: () => void }) {
  const toast = useToast();
  const [kind, setKind] = useState(need?.evidence_kind || "payments");
  const [message, setMessage] = useState(need ? `Please provide: ${need.reason}` : "");
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState<unknown>(null);
  async function submit(e: FormEvent) {
    e.preventDefault();
    setBusy(true); setError(null);
    try {
      await api(`/api/cases/${caseId}/info-requests`, { method: "POST", body: { evidence_kind: kind, message } });
      toast("ok", "Information requested. The case is now awaiting information.");
      onDone();
    } catch (err) { setError(err); } finally { setBusy(false); }
  }
  return (
    <Modal title="Request additional information" onClose={onClose}>
      <form onSubmit={submit} noValidate>
        <Field label="Evidence needed">
          <select value={kind} onChange={(e) => setKind(e.target.value)}>
            {Object.entries(KIND_LABEL).map(([k, v]) => <option key={k} value={k}>{v}</option>)}
          </select>
        </Field>
        <Field label="Message to the requester" hint="The request closes automatically when matching evidence is added.">
          <textarea rows={4} value={message} onChange={(e) => setMessage(e.target.value)} />
        </Field>
        <ErrorBlock error={error} />
        <div className="modal-actions">
          <button type="button" className="btn btn-quiet" onClick={onClose}>Cancel</button>
          <button className="btn btn-primary" disabled={busy}>{busy ? <Spinner /> : "Send request"}</button>
        </div>
      </form>
    </Modal>
  );
}
